server:
  port: 8090
  servlet:
    context-path: /wh
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanghuan?useSSL=false&amp;characterEncoding=utf-8&amp;jdbcCompliantTruncation=false&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.wanghuan.model

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.wanghuan: DEBUG