server:
  port: 8081

spring:
  datasoure:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/db_brp
    username: root
    password:
    druid:
      stat-view-servlet:
        allow: true

mybatis:
  type-aliases-package: tk.mybatis.springboot.model
  mapper-locations: classpath:mapper/*.mxl

mapper:
  mappers: tk.mybatis.springboot.util.MyMapper
  not-empty: false
  identity: MYSQL
